#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2014 Damien Nicolas <damien@gordon.re>
#
# Distributed under terms of the MIT license.

"""
This module reads specially-formatted files (in TPP format) and shows the
content as a presentation in text-based interface.
"""

import argparse
from tplusplus.controllers import ConversionController
from tplusplus.visualizers import TextVisualizer, NcursesVisualizer



if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Text Presentation Program '
                                     'Improved')
    parser.add_argument('--version', action='version', version='%(prog)s 0.8')
    parser.add_argument('-t', '--type',
                        action='store',
                        dest='type',
                        default='ncurses',
                        choices=('text', 'ncurses'),
                        help='set filetype TYPE as output format')
    parser.add_argument('-o', '--output',
                        metavar='out-file',
                        type=argparse.FileType('wt'),
                        action='store',
                        dest='output',
                        help='write output to file OUTPUT')
    parser.add_argument('file',
                        metavar='in-file',
                        type=argparse.FileType('rt'),
                        action='store',
                        help='TPP file to show')

    results = parser.parse_args()

    if results.type == 'text' and not results.output:
        parser.error('argument -o/--output is required')

    # print(results)

    visualizers = {'text': TextVisualizer, 'ncurses': NcursesVisualizer}

    try:
        ctrl = ConversionController(results.file,
                                    results.output,
                                    visualizers[results.type])
        ctrl.run()
        ctrl.close()

    except Exception as e:
        print(e.message)
